# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
# Tell setuptools to look for packages ONLY inside the 'src' directory
where = ["src"]

[project]
name = "vishals_adk_demo_agents"
version = "0.1.0"
authors = [
  { name="Vishal Patel", email="vishalapatel@google.com" },
]
description = "A collection of ADK example agents."
readme = "README.md"
requires-python = ">=3.10"

# Add the Agent Development Kit (ADK) as a dependency.
# You might need to adjust the version based on your requirements.
dependencies = [
    "google-adk>=1.12.0",
]


# This section defines a console script to easily run your agent.
# It assumes your agent's code is in a file named `my_agent.py` and
# that the main execution logic is wrapped in a `main()` function.
#
# To use this, you would modify your agent file's entry point like so:
#
# def main():
#     with agent_context_manager.AgentContextManager() as agent_context:
#         MyLlmAgent(agent_context).run()
#
# if __name__ == "__main__":
#     main()
#
# After installing the project (e.g., with `pip install .`),
# you can run your agent from the terminal with the command: `run-my-agent`
# [project.scripts]
# run-my-agent = "my_agent:main"

